# Generated by Django 3.2.16 on 2023-09-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230826_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='conference_active',
            new_name='blue_conference_room_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='orange_conference_room_active',
            field=models.BooleanField(default=True),
        ),
    ]
