# Generated by Django 3.2.16 on 2023-05-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('regulations', models.TextField()),
                ('opening_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookedHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_end_time', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_end_time', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='amenities')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmenityBooker.amenity')),
                ('hours_available', models.ManyToManyField(related_name='hours_available', to='AmenityBooker.Hour')),
                ('hours_booked', models.ManyToManyField(related_name='hours_booked', to='AmenityBooker.Hour')),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='hours',
            field=models.ManyToManyField(to='AmenityBooker.Hour'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='images',
            field=models.ManyToManyField(to='AmenityBooker.Images'),
        ),
    ]
