# Generated by Django 3.2.16 on 2023-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmenityBooker', '0002_alter_reservationmodel_hours_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='hours_booked',
            field=models.ManyToManyField(blank=True, related_name='hours_booked', to='AmenityBooker.Hour'),
        ),
    ]
