# Generated by Django 3.2.16 on 2023-05-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmenityBooker', '0004_userreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='amenity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AmenityBooker.amenity'),
            preserve_default=False,
        ),
    ]
