# Generated by Django 3.2.16 on 2023-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmenityBooker', '0005_userreservation_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='hours_available',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='hours_booked',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='hours_available_today',
            field=models.ManyToManyField(blank=True, related_name='hours_available_today', to='AmenityBooker.Hour'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='hours_available_tomorrow',
            field=models.ManyToManyField(blank=True, related_name='hours_available_tomorrow', to='AmenityBooker.Hour'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='hours_booked_today',
            field=models.ManyToManyField(blank=True, related_name='hours_booked_today', to='AmenityBooker.Hour'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='hours_booked_tomorrow',
            field=models.ManyToManyField(blank=True, related_name='hours_booked_tomorrow', to='AmenityBooker.Hour'),
        ),
    ]
