# Generated by Django 3.2.16 on 2023-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmenityBooker', '0006_auto_20230510_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
