# Generated by Django 3.2.16 on 2023-07-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmenityBooker', '0007_amenity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='additional_info',
            field=models.TextField(null=True),
        ),
    ]
