# Generated by Django 4.1.5 on 2023-08-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmenityBooker', '0008_amenity_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
